steps:
  - name: node
    dir: web
    entrypoint: npm
    args: ['install']
  - name: node
    dir: web
    entrypoint: npm
    args: ['run', 'build']
  - name: gcr.io/backslash-project/firebase
    dir: web
    args: ['deploy', '--project=backslash-project', '--only=hosting']