steps:
- name: node
  dir: vuepress
  entrypoint: npm
  args: [ 'install' ]
- name: node
  dir: vuepress
  entrypoint: npm
  args: [ 'run', 'build' ]
- name: gcr.io/backslash-project/firebase
  dir: vuepress
  args: [ 'deploy', '--project=backslash-project', '--only=hosting' ]
