steps:
- name: node
  dir: vitepress
  entrypoint: npm
  args: [ 'install' ]
- name: node
  dir: vitepress
  entrypoint: npm
  args: [ 'run', 'build' ]
- name: us-docker.pkg.dev/firebase-cli/us/firebase
  dir: vitepress
  args: [ 'deploy', '--project=backslash-project', '--only=hosting' ]
