steps:
  - name: npm install
    dir: web
    entrypoint: npm
    args: ['install']
  - name: npm build
    dir: web
    entrypoint: npm
    args: ['run', 'build']
  - name: gcr.io/backslash-project/firebase
    args: ['deploy', '--project=backslash-project', '--only=hosting']